
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://8.136.101.132:3305/haiyang?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
     #PKCS12
  #redis
  data:
    redis:
      database: 0
      port: 6379
      host: 8.136.101.132
      password: 123456
  servlet:
    multipart:
      max-file-size: 5MB #上传文件大小
  # 配置spring时区
  jackson:
    time-zone: GMT+8
  kafka: #kafka
    bootstrap-servers: 8.136.101.132:9092
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: operate_log
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#端口
server:
  port: 8080
# https证书配置
#  ssl:
#    key-store-type: PKCS12
#    key-store-password: r4novnnw
#    key-store: classpath:hhumarinegeology.top.pfx

#驼峰命名
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

#设置日志等级
logging:
  level:
    org.apache.kafka.clients.producer: warn


